# Generated by Django 4.0.6 on 2022-07-19 23:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beat', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='music/covers')),
                ('spotify_link', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=255, null=True)),
                ('soundcloud_link', models.CharField(blank=True, max_length=255, null=True)),
                ('deezer_link', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_music_link', models.CharField(blank=True, max_length=255, null=True)),
                ('yandex_music_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lyrics', ckeditor.fields.RichTextField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('cover_designer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_designer', to=settings.AUTH_USER_MODEL)),
                ('executive_producer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive_producer', to=settings.AUTH_USER_MODEL)),
                ('music_producer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_producer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
