# Generated by Django 4.0.6 on 2022-07-19 23:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lyrics',
            field=ckeditor.fields.RichTextField(max_length=10000),
        ),
    ]
