# Generated by Django 4.0.6 on 2022-07-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0003_alter_track_cover_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='feat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_designer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='executive_producer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='music_producer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
