# Generated by Django 4.0.6 on 2022-07-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0004_track_feat_alter_track_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/prof_pics')),
            ],
        ),
    ]
