# Generated by Django 4.0.6 on 2022-07-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0006_album_profile_apple_music_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateField(),
        ),
    ]
