# Generated by Django 4.0.6 on 2022-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0007_alter_track_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='amazon_buy_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='itunes_buy_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='napster_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='qobuz_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='tidal_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_music_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
