# Generated by Django 4.0.6 on 2022-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0008_track_amazon_buy_link_track_amazon_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tidal_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
