# Generated by Django 4.0.6 on 2022-08-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0009_profile_tidal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateField(),
        ),
    ]
