# Generated by Django 4.0.6 on 2022-08-10 02:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0010_alter_album_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/products')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YuzQirxApp.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YuzQirxApp.size')),
            ],
        ),
    ]
