# Generated by Django 4.0.6 on 2022-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuzQirxApp', '0013_rename_productimages_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
